alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: crawl4ai
region: nyc
services:
- dockerfile_path: Dockerfile
  github:
    branch: 0.3.74
    deploy_on_push: true
    repo: unclecode/crawl4ai 
  health_check:
    http_path: /health
  http_port: 11235
  instance_count: 1
  instance_size_slug: professional-xs
  name: web
  routes:
  - path: /